# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- release/demo

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'bes-dev-test-container-registry'
  containerAppServiceConnection: 'az-container-app-deploy-bes-dev-sc'
  containerAppResourceGroup: 'BES-DEV'
  containerAppName: 'bes-portal-demo'
  imageRepository: 'bes-portal'
  containerRegistry: 'besdevtestcontainerregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)-demo'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: --build-arg BUILD_CONFIG=Demo
        Dockerfile: $(dockerfilePath)
        repository: $(imageRepository)
        buildContext: '$(Build.Repository.LocalPath)'
        tags: $(tag)

    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

    - task: AzureCLI@2
      displayName: 'Deploy app to Container App'
      inputs:
        azureSubscription: $(containerAppServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: | 
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name '$(containerAppName)' \
            --resource-group '$(containerAppResourceGroup)' \
            --image '$(containerRegistry)'/'$(imageRepository)':'$(tag)'